In [1]:
import torch
import numpy as np

## Data Type

### Type Check

In [7]:
a = torch.randn(2,3)
# rand from N(0,1), shape of [2,3]

In [4]:
a.type()

'torch.FloatTensor'

In [5]:
type(a)

torch.Tensor

In [6]:
isinstance(a, torch.FloatTensor)

True

In [12]:
data = torch.DoubleTensor(2,3)
isinstance(data, torch.cuda.DoubleTensor)
# data in CPU

False

In [13]:
data = data.cuda()
isinstance(data, torch.cuda.DoubleTensor)
# data in GPU
# .cuda() returns a reference in GPU

True

### Dimension 0 / rank 0
Loss

In [15]:
torch.tensor(1.)

tensor(1.)

In [14]:
torch.tensor(1.3)

tensor(1.3000)

In [16]:
a = torch.tensor(2.2)
a.shape

torch.Size([])

In [17]:
len(a.shape)

0

In [18]:
a.size()

torch.Size([])

### Dimension 1 / rank 1
Bias, Linear Input

In [19]:
torch.tensor([1.1])
# .tensor get the data itself

tensor([1.1000])

In [20]:
torch.tensor([1.1, 2.2])

tensor([1.1000, 2.2000])

In [21]:
torch.FloatTensor(1)
# .FloatTensor get the shape of data

tensor([9.1477e-41])

In [22]:
torch.FloatTensor(2)

tensor([1.4013e-45, 0.0000e+00])

In [25]:
data = np.ones(2)
data

array([1., 1.])

In [26]:
torch.from_numpy(data)

tensor([1., 1.], dtype=torch.float64)

### Dimension 2 
Linear input with batch

In [27]:
a = torch.randn(2, 3)
a

tensor([[ 1.1618, -0.0635, -2.5531],
        [ 1.9363, -0.4735, -0.8492]])

In [28]:
a.shape

torch.Size([2, 3])

In [30]:
a.size(0)

2

In [32]:
a.shape[1]

3

### Dimension 3
RNN input with Batch

In [33]:
a = torch.rand(1,2,3)
a

tensor([[[0.7077, 0.7945, 0.2229],
         [0.0711, 0.2299, 0.6192]]])

In [34]:
a.shape

torch.Size([1, 2, 3])

In [35]:
a[0]

tensor([[0.7077, 0.7945, 0.2229],
        [0.0711, 0.2299, 0.6192]])

In [36]:
list(a.shape)

[1, 2, 3]

### Dimension 4
Image CNN with Batch

In [37]:
a = torch.rand(2,3,28,28)
a

tensor([[[[0.9452, 0.0960, 0.6244,  ..., 0.3075, 0.1940, 0.0176],
          [0.7156, 0.6183, 0.0516,  ..., 0.7265, 0.1831, 0.9007],
          [0.5959, 0.5855, 0.5469,  ..., 0.6994, 0.7649, 0.7002],
          ...,
          [0.4662, 0.7795, 0.5231,  ..., 0.5171, 0.3908, 0.8164],
          [0.2073, 0.2678, 0.9561,  ..., 0.1791, 0.2662, 0.5499],
          [0.2395, 0.9327, 0.6420,  ..., 0.1753, 0.4115, 0.2605]],

         [[0.0512, 0.2766, 0.1153,  ..., 0.7260, 0.2298, 0.4059],
          [0.8101, 0.0701, 0.4313,  ..., 0.4626, 0.3031, 0.6003],
          [0.1870, 0.6604, 0.5217,  ..., 0.9018, 0.6958, 0.3204],
          ...,
          [0.6748, 0.4852, 0.6504,  ..., 0.2738, 0.4558, 0.1826],
          [0.9928, 0.3344, 0.3784,  ..., 0.3541, 0.1814, 0.5361],
          [0.0516, 0.3984, 0.5477,  ..., 0.5774, 0.3418, 0.1017]],

         [[0.0853, 0.7975, 0.3340,  ..., 0.0397, 0.5973, 0.4044],
          [0.1200, 0.7229, 0.5175,  ..., 0.9498, 0.6407, 0.0195],
          [0.6015, 0.9320, 0.9014,  ..., 0

In [38]:
a.shape

torch.Size([2, 3, 28, 28])

### Mixed

In [39]:
a.numel()
# the size of the numbers

4704

In [40]:
a.dim()

4

## Generate Tensor

### Import from numpy

In [41]:
a = np.array([2,3.3])
torch.from_numpy(a)
# It's Double

tensor([2.0000, 3.3000], dtype=torch.float64)

In [43]:
a = np.ones([2,3])
torch.from_numpy(a)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

### Import from List

In [46]:
torch.tensor([[2.,3.2],[1.,22.3]])

tensor([[ 2.0000,  3.2000],
        [ 1.0000, 22.3000]])

### uninitialized
torch.empty()
torch.FloatTensor(d1,d2,d3)
torch.IntTensor(d1,d2,d3)

In [47]:
torch.empty(1)

tensor([9.1477e-41])

In [48]:
torch.Tensor(2,3)

tensor([[1.0745e-38, 1.1112e-38, 9.2755e-39],
        [2.9389e-39, 1.0194e-38, 9.2755e-39]])

In [49]:
torch.IntTensor(2,3)

tensor([[ 892744754, 1650746678,  878916403],
        [ 875836515,  845374818,  875575353]], dtype=torch.int32)

In [50]:
torch.FloatTensor(2,3)

tensor([[1.0616e+21, 5.4884e-05, 2.6367e-09],
        [1.7186e-04, 6.7371e-10, 2.5930e-09]])

### set default type
In reinforcement learning, double; float in other cases

In [51]:
torch.tensor([1.2,3]).type()

'torch.FloatTensor'

In [52]:
torch.set_default_tensor_type(torch.DoubleTensor)

In [53]:
torch.tensor([1.2,3]).type()

'torch.DoubleTensor'

### rand / rand_like, randint
(0,1), *_like, (min, max)

In [54]:
torch.rand(3,3)

tensor([[0.0607, 0.2920, 0.2369],
        [0.6395, 0.8671, 0.0904],
        [0.7570, 0.6274, 0.8076]])

In [55]:
a = torch.rand(3,3)
torch.rand_like(a)

tensor([[0.4734, 0.9697, 0.9647],
        [0.8702, 0.5200, 0.8311],
        [0.5481, 0.8309, 0.5695]])

In [58]:
torch.randint(1,10,[3,3])

tensor([[2, 6, 5],
        [4, 7, 5],
        [2, 6, 6]])

### randn
N(0,1)

In [59]:
torch.randn(3,3)

tensor([[-0.9187, -0.7687,  0.3792],
        [ 0.6249, -0.0134, -0.6309],
        [ 0.4018,  0.0097, -0.1958]])

In [66]:
# torch.normal(mean=torch.full([10],0), std=torch.arange(1,0,-0.1))

### full

In [67]:
torch.full([2,3],7)

tensor([[7, 7, 7],
        [7, 7, 7]])

In [68]:
torch.full([],7)

tensor(7)

In [69]:
torch.full([1],7)

tensor([7])

### arange / range

In [70]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [72]:
torch.range(0,10)

<ipython-input-72-dfdec9b83f7d>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

### linspace / logspace

In [73]:
torch.linspace(0,10, steps=4)

tensor([ 0.0000,  3.3333,  6.6667, 10.0000])

In [74]:
torch.linspace(0,10, steps=10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [75]:
torch.linspace(0,10, steps=11)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [76]:
torch.logspace(0,-1, steps=10)
# the base para can be set to 2, 10, e

tensor([1.0000, 0.7743, 0.5995, 0.4642, 0.3594, 0.2783, 0.2154, 0.1668, 0.1292,
        0.1000])

In [77]:
torch.logspace(0,1, steps=10)

tensor([ 1.0000,  1.2915,  1.6681,  2.1544,  2.7826,  3.5938,  4.6416,  5.9948,
         7.7426, 10.0000])

### ones / zeros / eye

In [78]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [79]:
torch.zeros(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [80]:
torch.eye(3,4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])

### randperm
random.shuffle

In [128]:
a = torch.rand(2,3)
b = torch.rand(2,2)
idx = torch.randperm(2)
# the seed

In [130]:
a[idx]

tensor([[0.3607, 0.0586, 0.8555],
        [0.5020, 0.8972, 0.2484]])

## Index and Cut

### Indexing

In [131]:
a = torch.rand(4,3,28,28)
a[0].shape
# indexing from the left

torch.Size([3, 28, 28])

In [132]:
a[0,0].shape

torch.Size([28, 28])

In [133]:
a[0,0,2,4]

tensor(0.0741)

### select first / last N

In [134]:
a[:2].shape

torch.Size([2, 3, 28, 28])

In [135]:
a[:2,:1,:,:].shape

torch.Size([2, 1, 28, 28])

In [136]:
a[:2,1:,:,:].shape

torch.Size([2, 2, 28, 28])

In [137]:
a[:2,-1:,:,:].shape
# the last is -1

torch.Size([2, 1, 28, 28])

### select by steps

In [138]:
a[:,:,0:28:2,0:28:2].shape

torch.Size([4, 3, 14, 14])

In [139]:
a[:,:,::2,::2].shape

torch.Size([4, 3, 14, 14])

### select by specific index

In [140]:
a.index_select(0,torch.tensor([0,2])).shape
# select 0th dim data

torch.Size([2, 3, 28, 28])

In [142]:
a.index_select(1,torch.tensor([1,2])).shape

torch.Size([4, 2, 28, 28])

In [143]:
a.index_select(2,torch.arange(28)).shape

torch.Size([4, 3, 28, 28])

In [144]:
a.index_select(2,torch.arange(8)).shape

torch.Size([4, 3, 8, 28])

### ...

In [145]:
a[...].shape

torch.Size([4, 3, 28, 28])

In [146]:
a[0,...].shape

torch.Size([3, 28, 28])

In [147]:
a[:,1,...].shape

torch.Size([4, 28, 28])

### select by mask
.masked_select()

In [149]:
x = torch.randn(3,4)
x

tensor([[ 1.1133, -0.4800,  0.7728,  0.4351],
        [ 0.5779, -1.0344,  0.6008, -0.2606],
        [-1.0106, -0.3813, -1.6270,  0.3401]])

In [151]:
mask = x.ge(0.5)
# greater equal; ByteTensor
mask

tensor([[ True, False,  True, False],
        [ True, False,  True, False],
        [False, False, False, False]])

In [152]:
torch.masked_select(x, mask)

tensor([1.1133, 0.7728, 0.5779, 0.6008])

In [153]:
torch.masked_select(x, mask).shape

torch.Size([4])

### select by flatten index

In [154]:
src = torch.tensor([[4,3,5],[6,7,8]])

In [155]:
torch.take(src,torch.tensor([0,2,5]))

tensor([4, 5, 8])

## Tensor Dimension Transfor
* view / reshape
* squeeze / unsqueeze
* transpose / t / permute
* expand / repeat

### view / reshape

In [156]:
a = torch.rand(4,1,28,28)
a.shape

torch.Size([4, 1, 28, 28])

In [157]:
a.view(4,28*28)

tensor([[0.1464, 0.2592, 0.2137,  ..., 0.6203, 0.6279, 0.4592],
        [0.6888, 0.3686, 0.8775,  ..., 0.3916, 0.5888, 0.4738],
        [0.6553, 0.3024, 0.7099,  ..., 0.5065, 0.2029, 0.9644],
        [0.5989, 0.9113, 0.6837,  ..., 0.5471, 0.0574, 0.8133]])

In [158]:
# b = a.view(4,28*28)
# b.view(4,28,28,1)
# this is a logic bug!!! the dimension rank is important

### squeeze v.s. unsqueeze
[-a.dim()-1, a.dim()+1)

In [159]:
a.shape

torch.Size([4, 1, 28, 28])

In [160]:
a.unsqueeze(0).shape

torch.Size([1, 4, 1, 28, 28])

In [161]:
a.unsqueeze(-1).shape
# it wouldn't change the data, but the shape of the organization

torch.Size([4, 1, 28, 28, 1])

In [162]:
a = torch.tensor([1.2,2.3])
# shape [2]

In [163]:
a.unsqueeze(-1)
# shape [2] -> [2,1]

tensor([[1.2000],
        [2.3000]])

In [164]:
a.unsqueeze(0)
# shape [2] -> [1,2]

tensor([[1.2000, 2.3000]])

In [165]:
# for example
b = torch.rand(32)
f = torch.rand(4,32,14,14)
# we want f+b
b = b.unsqueeze(1).unsqueeze(2).unsqueeze(0)
b.shape

torch.Size([1, 32, 1, 1])

In [166]:
b.squeeze().shape

torch.Size([32])

In [167]:
b.squeeze(0).shape

torch.Size([32, 1, 1])

In [168]:
b.squeeze(1).shape

torch.Size([1, 32, 1, 1])

### expand / repeat
expand: broadcasting
repeat: memory copied

In [169]:
a = torch.rand(4,32,14,14)
b.shape

torch.Size([1, 32, 1, 1])

In [170]:
b.expand(4,32,14,14).shape

torch.Size([4, 32, 14, 14])

In [171]:
b.expand(-1,32,-1,-1).shape
# -1 means no change

torch.Size([1, 32, 1, 1])

In [172]:
b.repeat(4,32,1,1).shape
# times of repeat

torch.Size([4, 1024, 1, 1])

### .t
expects a 2 dim tensor, but **self** is >2 dim

### transpose

In [179]:
a = torch.rand(4,3,32,32)

In [182]:
a1 = a.transpose(1,3).contiguous().view(4,3*32*32).view(4,3,32,32)

In [181]:
a2 = a.transpose(1,3).contiguous().view(4,3*32*32).view(4,32,32,3).transpose(1,3)

In [183]:
a1.shape, a2.shape
# view will blur the order of dimensions, it needs to be tracked

(torch.Size([4, 3, 32, 32]), torch.Size([4, 3, 32, 32]))

In [184]:
torch.all(torch.eq(a,a1)), torch.all(torch.eq(a,a2))

(tensor(False), tensor(True))

### permute

In [187]:
a = torch.rand(4,3,28,32)
# [b, c, H, W]

In [188]:
# [b, c, H, W] -> [b, H, W, c]
a.transpose(1,3).transpose(1,2).shape

torch.Size([4, 28, 32, 3])

In [189]:
a.permute(0,2,3,1).shape

torch.Size([4, 28, 32, 3])

## Broadcasting
* Insert 1 dim ahead
* Expand dims with size 1 to same size
    * Feature maps: [4, 32, 14, 14]
    * Bias: [32, 1, 1] => [1, 32, 1, 1] => [4, 32, 14, 14]
* Is it broadcasting-able?
    * Match from Last dim
    * If current dim=1, expand to same
    * If rither has no dim, insert one dim and expand to same
    * otherwise, NOT broadcasting-able

## Merge or split
* Cat
* Stack
* Split
* Chunk

### Cat

In [2]:
a = torch.rand(4,32,8)
b = torch.rand(5,32,8)

In [3]:
torch.cat([a,b],dim=0).shape

torch.Size([9, 32, 8])

In [4]:
a1 = torch.rand(4,3,32,32)
a2 = torch.rand(5,3,32,32)
torch.cat([a1,a2],dim=0).shape

torch.Size([9, 3, 32, 32])

In [5]:
a2 = torch.rand(4,1,32,32)
torch.cat([a1,a2],dim=1).shape

torch.Size([4, 4, 32, 32])

 ### Stack
 creat new dim

In [6]:
a = torch.rand(32,8)
b = torch.rand(32,8)
torch.stack([a,b],dim=0).shape

torch.Size([2, 32, 8])

### Cat v.s. stack

In [7]:
a = torch.rand(32,8)
b = torch.rand(30,8)

In [8]:
torch.stack([a,b],dim=0)

RuntimeError: stack expects each tensor to be equal size, but got [32, 8] at entry 0 and [30, 8] at entry 1

In [9]:
torch.cat([a,b],dim=0).shape

torch.Size([62, 8])

### Split: by len

In [11]:
a = torch.rand(32,8)
b = torch.rand(32,8)
c = torch.stack([a,b],dim=0)
c.shape

torch.Size([2, 32, 8])

In [12]:
aa, bb = c.split([1,1],dim=0)
aa.shape, bb.shape

(torch.Size([1, 32, 8]), torch.Size([1, 32, 8]))

In [13]:
aa, bb = c.split(1,dim=0)
aa.shape, bb.shape

(torch.Size([1, 32, 8]), torch.Size([1, 32, 8]))

### Chunk: by num

In [14]:
a = torch.rand(32,8)
b = torch.rand(32,8)
c = torch.stack([a,b],dim=0)
c.shape

torch.Size([2, 32, 8])

In [15]:
aa, bb = c.chunk(2,dim=0)
aa.shape, bb.shape

(torch.Size([1, 32, 8]), torch.Size([1, 32, 8]))