In [1]:
import torch

## Math operation
* Add / minus / multiply / divide
* Matmul
* Pow
* Sqrt / rsqrt
* Round

### basic

In [2]:
a = torch.rand(3,4)
b = torch.rand(4)
a+b

tensor([[0.8682, 1.5696, 0.6674, 1.3955],
        [1.1416, 1.0818, 0.9862, 1.4133],
        [0.9876, 1.1756, 0.3821, 1.0367]])

In [3]:
torch.add(a,b)

tensor([[0.8682, 1.5696, 0.6674, 1.3955],
        [1.1416, 1.0818, 0.9862, 1.4133],
        [0.9876, 1.1756, 0.3821, 1.0367]])

In [6]:
torch.all(torch.eq(a-b,torch.sub(a,b)))

tensor(True)

In [7]:
torch.all(torch.eq(a*b,torch.mul(a,b)))

tensor(True)

In [8]:
torch.all(torch.eq(a/b,torch.div(a,b)))

tensor(True)

### Matmul
* torch.mm
    * only for 2 dim
* torch.matmul
* @

In [9]:
a = torch.ones(2,2)*3
a

tensor([[3., 3.],
        [3., 3.]])

In [10]:
b = torch.ones(2,2)
b

tensor([[1., 1.],
        [1., 1.]])

In [11]:
torch.mm(a,b)

tensor([[6., 6.],
        [6., 6.]])

In [12]:
torch.matmul(a,b)

tensor([[6., 6.],
        [6., 6.]])

In [13]:
a@b

tensor([[6., 6.],
        [6., 6.]])

In [15]:
# for example
x = torch.rand(4,784)
w = torch.rand(512,784)
(x@w.t()).shape

torch.Size([4, 512])

In [16]:
a = torch.rand(4,3,28,64)
b = torch.rand(4,3,64,32)
torch.matmul(a,b).shape
# [28,64] * [64,32] ->[28,32]

torch.Size([4, 3, 28, 32])

In [17]:
b = torch.rand(4,1,64,32)
torch.matmul(a,b).shape
# broadingcast

torch.Size([4, 3, 28, 32])

### Power sqrt rsqrt

In [18]:
a = torch.full([2,2],3)
a.pow(2)

tensor([[9, 9],
        [9, 9]])

In [21]:
aa = a**2
aa.sqrt()

tensor([[3., 3.],
        [3., 3.]])

In [22]:
aa.rsqrt()

tensor([[0.3333, 0.3333],
        [0.3333, 0.3333]])

In [24]:
a = torch.exp(torch.ones(2,2))
a

tensor([[2.7183, 2.7183],
        [2.7183, 2.7183]])

In [25]:
torch.log(a)

tensor([[1., 1.],
        [1., 1.]])

### Approximation
* .floor() .ceil()
* .round()
* .trunc() .frac()

In [26]:
a = torch.tensor(3.14)
a.floor(), a.ceil(), a.trunc(), a.frac()

(tensor(3.), tensor(4.), tensor(3.), tensor(0.1400))

In [27]:
a = torch.tensor(3.499)
a.round()

tensor(3.)

In [28]:
a = torch.tensor(3.5)
a.round()

tensor(4.)

### Clamp
* gradient clipping
* (min)
* (min,max)

In [32]:
grad = torch.rand(2,3)*15
grad.max(), grad.median(), grad.clamp(10), grad
# if grad < 10, make it = 10

(tensor(13.9923),
 tensor(6.7363),
 tensor([[10.0000, 10.0000, 13.9923],
         [10.0000, 10.0000, 10.0000]]),
 tensor([[ 3.2530,  9.0721, 13.9923],
         [ 1.3586,  6.7363,  9.7196]]))

In [33]:
grad.clamp(0,10)
# if grad > 10, make it =10

tensor([[ 3.2530,  9.0721, 10.0000],
        [ 1.3586,  6.7363,  9.7196]])