In [2]:
import torch

## Statistics
* norm
* mean sum
* prod
* max, min, argmin, argmax
* kthvalue, topk

### norm-p


In [6]:
a = torch.full([8],1.)
b = a.view(2,4)
c = a.view(2,2,2)

In [7]:
a.norm(1),b.norm(1),c.norm(1)

(tensor(8.), tensor(8.), tensor(8.))

In [8]:
a.norm(2),b.norm(2),c.norm(2)

(tensor(2.8284), tensor(2.8284), tensor(2.8284))

In [10]:
b.norm(1,dim=1), b.norm(2,dim=1)

(tensor([4., 4.]), tensor([2., 2.]))

In [13]:
c.norm(1, dim=0), c.norm(2, dim=0)

(tensor([[2., 2.],
         [2., 2.]]),
 tensor([[1.4142, 1.4142],
         [1.4142, 1.4142]]))

### mean, sum, min, max, prod

In [18]:
a = torch.arange(8).view(2,4).float()
a

tensor([[0., 1., 2., 3.],
        [4., 5., 6., 7.]])

In [20]:
a.min(), a.max(), a.mean(), a.prod(), a.sum()

(tensor(0.), tensor(7.), tensor(3.5000), tensor(0.), tensor(28.))

In [21]:
a.argmax(), a.argmin()

(tensor(7), tensor(0))

In [22]:
a = torch.randn(4,10)
a[0]

tensor([ 0.2772,  0.3845,  0.1878,  0.1184,  0.5666,  0.8003, -0.3315,  0.1877,
         0.6845, -0.9124])

In [23]:
a.argmax(), a.argmin()

(tensor(24), tensor(36))

In [24]:
a.argmax(dim=1), a.argmin(dim=1)

(tensor([5, 5, 4, 8]), tensor([9, 6, 1, 6]))

### dim, keepdim

In [25]:
a.max(dim=1), a.argmax(dim=1)
# [4,10] ->[4],[4]

(torch.return_types.max(
 values=tensor([0.8003, 1.1590, 2.2884, 2.0594]),
 indices=tensor([5, 5, 4, 8])),
 tensor([5, 5, 4, 8]))

In [26]:
a.max(dim=1,keepdim=True), a.argmax(dim=1,keepdim=True)
# [4,10] ->[4,1],[4,1]

(torch.return_types.max(
 values=tensor([[0.8003],
         [1.1590],
         [2.2884],
         [2.0594]]),
 indices=tensor([[5],
         [5],
         [4],
         [8]])),
 tensor([[5],
         [5],
         [4],
         [8]]))

### top-k or k-th
* .topk
    * largest
* kthvalue

In [27]:
a = torch.randn(4,10)

In [28]:
a.topk(3,dim=1)
# largest topk

torch.return_types.topk(
values=tensor([[ 3.0830,  0.8120,  0.3977],
        [ 0.7366,  0.5481,  0.4729],
        [ 0.6792,  0.3566, -0.1030],
        [ 2.6085,  1.3539,  0.9137]]),
indices=tensor([[3, 8, 9],
        [7, 4, 3],
        [1, 9, 5],
        [0, 8, 3]]))

In [30]:
a.topk(3,dim=1,largest=False)
# least topk

torch.return_types.topk(
values=tensor([[-2.0207, -1.7647, -1.2984],
        [-1.7875, -0.5831, -0.3301],
        [-2.0103, -1.2407, -0.6850],
        [-0.8926, -0.4624, -0.2524]]),
indices=tensor([[0, 6, 4],
        [9, 1, 2],
        [6, 3, 4],
        [7, 6, 1]]))

In [31]:
a.kthvalue(8,dim=1)
# least k-th

torch.return_types.kthvalue(
values=tensor([ 0.3977,  0.4729, -0.1030,  0.9137]),
indices=tensor([9, 3, 5, 3]))

### compare
* '>, >=, <, <=, !=, =='
* torch.eq(a,b)
    * torch.equal(a,b)

In [35]:
a>0

tensor([[False, False,  True,  True, False, False, False, False,  True,  True],
        [ True, False, False,  True,  True,  True,  True,  True,  True, False],
        [False,  True, False, False, False, False, False, False, False,  True],
        [ True, False,  True,  True,  True,  True, False, False,  True,  True]])

In [36]:
torch.gt(a,0)

tensor([[False, False,  True,  True, False, False, False, False,  True,  True],
        [ True, False, False,  True,  True,  True,  True,  True,  True, False],
        [False,  True, False, False, False, False, False, False, False,  True],
        [ True, False,  True,  True,  True,  True, False, False,  True,  True]])

In [37]:
a!=0

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])

In [39]:
b = torch.ones(4,10)
torch.eq(a,b)

tensor([[False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False]])

In [40]:
torch.equal(a,b)

False

## Tensor advanced operation
* where
* gather

### where
* torch.where(condition,x,y) -> Tensor
    * Return a tensor of elements selected from either *x* or *y*, depending on *condition*. 
    * out_i = x_i, if condition_i; out_i = y_i, otherwise

In [42]:
cond = torch.rand(2,2)
cond

tensor([[0.7482, 0.4162],
        [0.6800, 0.9378]])

In [48]:
a = torch.full([2,2],0.)
b = torch.ones(2,2).float()
torch.where(cond>0.5,a,b)

tensor([[0., 1.],
        [0., 0.]])

### gather
* torch.gather(input,dim,index,out=None) -> Tensor
    * Gathers values along an axis specified by dim.
    * For a 3 dim tensor the output is specified by:
    * out[i][j][k] = input[index[i][j][k]][j][k]  if dim == 0
    * out[i][j][k] = input[i][index[i][j][k]][k]  if dim == 1
    * out[i][j][k] = input[i][j][index[i][j][k]]  if dim == 2
* retrieve global label
    * argmax(pred) to get relative labeling
    * on some condition, our label is dinsitinct from relative labeling

In [6]:
prob = torch.randn(4,10)
idx = prob.topk(dim=1, k=3)
idx = idx[1]
label = torch.arange(10)+100
torch.gather(label.expand(4,10),dim=1,index=idx.long())

tensor([[109, 101, 105],
        [103, 105, 109],
        [100, 105, 106],
        [105, 100, 104]])